include:
  - project: 'toomba-labs/toomba-pipelines'
    ref: "master"
    file: '/commandbox/gitlab-ci-flyway.yml'

variables:
  # Application deployment domain
  KUBE_DOMAIN: k8s.mytoomba.nl
  # Use the following healthcheck if the other keeps failing
  # this will probably be because of DB sync taking to long...
  GKE_POD_LIVENESSPROBE_INITIAL_DELAY: '180'
  GKE_POD_READINESSPROBE_INITIAL_DELAY: '180'

  CI_ENVIRONMENT_URL: https://${CI_PROJECT_NAME}-${CI_ENVIRONMENT_SLUG}.${KUBE_DOMAIN}

  # ip whitelist. Relocation office, Spanish office, Holland office, Sander Home, Gitlab Caspejs
  GKE_NGINX_INGRESS_WHITELIST: "145.131.124.8,213.96.31.193,80.127.144.82,86.84.22.96,23.251.129.108"

# TODO: set to correct upload folder
  GKE_PVC_CREATE: 'true'
  GKE_PVC_SIZE: '10Gi'
  GKE_PVC_MOUNT_DIR: '/app/application/uploads'

# Lucee datasource settings
  POD_LUCEE_DB_DATASOURCE: 'preside'
  POD_LUCEE_DB_USERNAME: 'toombademo_user'
  POD_LUCEE_DB_PASSWORD: 'Z3U95WriiNYY89ak'
  POD_LUCEE_DB_HOST: 'localhost'
  POD_LUCEE_DB_NAME: 'toombademo'
  POD_LUCEE_APPLICATION_SESSIONSTORAGE: 'preside'

# Flyway config
  DB_HOST: 'db1.toomba.nl'
  DB_PORT: '3306'
  DB_NAME: '${POD_LUCEE_DB_NAME}'
  DB_USER: '${POD_LUCEE_DB_USERNAME}'
  DB_PASS: '${POD_LUCEE_DB_PASSWORD}'
  DB_AUTO_CREATE_USER: 'true'


    # PresideCMS settings
  POD_PRESIDE_APPLICTION_ID: 'toombademo'
  POD_PRESIDE_showerrors: 'true'
  POD_PRESIDE_autosyncdb: 'true'
  CI_DEBUG_TRACE: 'true'
